### ISSUE TITLE
reconnect isnt backing off

### ISSUE THREAD

**Issue by ghost** [dominictarr/reconnect#13]
HI! Ive got some simple code just to test out the backoff part of reconnect.  It just doesnt seem to do it.  What happens is reconnect will just keep trying to reconnect every time interval which lies between initialDelay and manDelay.  I've tried out backoff proper, alone, and it works as advertised.  So I figure the problem may lie somewhere in reconnect.

Any thoughts on what might be wrong?

Heres my code.    

```

var reconnect = require('reconnect/http')
var through = require('through')

var opts = {
    uri: 'http://shit.url.moc'
}

var backoffOpts = {
    randomisationFactor: 0,
    initialDelay: 500,
    maxDelay: 1000
}

var s

var r = reconnect(backoffOpts, function (stream) {

  stream
  .pipe(through(function (data) {
    console.log(data)
  }))

})

var count = 0

r.on('disconnect', function (stream) {
  console.log('disconnected')
})
.on('backoff', function (attempts, delay) {
  console.log('backing off', attempts, delay)
})
.on('reconnect', function (attempts, delay) {
  console.log('reconnecting', attempts, delay)
  console.log(++count)
})
.connect(opts)
```

**Comment by dominictarr** [comment]
I havn't noticed any problem with this - it might help if you use a wider range your are asking it to reconnect between 0.5 seconds and 1 second, which probably isn't very noticeable anyway.

can you try expanding your range?

There is also a `reconnect.widget()` which you can add to your page, and it will show how long until the next connection attempt, and whether you currently have a connection.

**Comment by ghost** [comment]
duh moment of the day.  That range was totally it.  I wasnt realizing what maxDelay actually meant. Thanks!

**Comment by dominictarr** [comment]
no problem!
