### ISSUE TITLE
opts ignored

### ISSUE THREAD

**Issue by juliangruber** [dominictarr/reconnect#21]
by @rvagg in https://github.com/dominictarr/reconnect/issues/20#issuecomment-29455902:

>  [here](https://github.com/dominictarr/reconnect/blob/10a57198ff4a3d69aa9fe3fe845b6d11ac4e33ad/inject.js#L8), opts will be assigned to a function if that's all that's supplied, it should be doing a `typeof opts == 'object'` before assuming that it's good to use

**Comment by juliangruber** [comment]
i fixed this in reconnect-core: https://github.com/juliangruber/reconnect-core/commit/823cf0a96d378d1d9238767fa0ac4c48a70cc0df

**Comment by dominictarr** [comment]
hey, @juliangruber, adding you to reconnect

**Comment by dominictarr** [comment]
lets make reconnect@2 just be reconnect-core, and just have one repo.
Okay, Ill have a look at this in the morning.

**Comment by juliangruber** [comment]
sweet!

**Comment by nrw** [comment]
we might do well to move the examples over, too!

**Comment by dominictarr** [comment]
@nrw move the examples into reconnect-core?

by the way, this is now fixed and reconnect just depends on reconnect-core

**Comment by nrw** [comment]
@dominictarr i now see that this just depends on `reconnect-core`. :)

regarding the examples: i think the `reconnect-core` repository would benefit from more examples. this repo has a few more. maybe i'm just advocating for a link in the `reconnect-core` readme to these examples.

**Comment by dominictarr** [comment]
agree - a link is the simplest way.
