### ISSUE TITLE
no messages are received from the server

### ISSUE THREAD

**Issue by nrw** [dominictarr/reconnect#22]
Here's a minimal example of what i'm running into. The connection is made, but messages only transmit from client to server. If i pull out `reconnect` and replace it with `remote = shoe("/sock")`, everything works as expected. Did i skip something specific to reconnect or is this a bug?

``` javascript
// node server.js
var fs, http, server, shoe, sock, through;

http = require('http');
fs = require('fs');
shoe = require('shoe');
through = require('through');

// http server
server = http.createServer(function(req, res) {
  console.log('path', req.url);
  if (req.url === '/bundle.js') {
    return res.end(fs.readFileSync("" + __dirname + "/bundle.js"));
  } else if (req.url === '/') {
    return res.end("<!DOCTYPE html><html><head><title></title>"+
      "<script type='text/javascript' src='/bundle.js'></script>"+
      "</head><body><div id='result'></div></body></html>");
  } else {
    return res.end('404');
  }
});

// streaming sockjs
sock = shoe(function(remote) {
  var caps;
  caps = through(function(msg) {
    console.log('server received message:', msg);
    return this.queue(msg.toString().toUpperCase());
  });
  return remote.pipe(caps).pipe(remote);
});

sock.install(server, '/sock');

server.listen(3333);
```

``` javascript
// client
var domready, reconnect, through;

through = require('through');
domready = require('domready');
reconnect = require('reconnect/shoe');

domready(function() {
  var r, result;
  result = document.getElementById('result');

  // establish reconnections
  r = reconnect(function(remote) {
    var instream, outstream;
    // the stream we'll type into
    instream = through();

    // the stream that comes back from the server
    outstream = through(function(msg) {
      console.log("client received message:", msg);
      result.textContent += "client received message: " + msg;
      return this.queue(msg);

    });

    instream.pipe(remote).pipe(outstream);

    // make sure the write stream is accessible from the console
    window.stream = instream;

  }).connect('/sock');

  document.body.appendChild(r.widget());
});
```

Then, in the browser console:

``` javascript
stream.write('example message')
```

**Comment by nrw** [comment]
There's a gist of my testing code here: https://gist.github.com/nrw/8721623

**Comment by nrw** [comment]
replacing `client.js` line 6 (`reconnect = require('reconnect/shoe')`) with this `reconnect = require('reconnect/shoe-client')` makes it work. Is this an issue with how it's being processed by `browserify`? Or just a documentation error? The `shoe` example in this repository has this same problem.

**Comment by dominictarr** [comment]
okay, this is confirmed.

by they way, it's much easier to get up to speed if the issue is reproducable automatically,
... in this case, I would have sent messages from the client inside  a `setInterval`,
also, and also described clearly what you expected to see.

weird - okay - so this works if you use shoe directly with juliangruber's reconnect-core

**Comment by dominictarr** [comment]
okay - if you load reconnect/shoe-client directly it works. so, yes this is about browserify.

**Comment by dominictarr** [comment]
okay, I've updated reconnect@2.0.0 to depend on reconnect-core,
and I recommend just using reconnect-core directly.

``` js
var reconnect = require('reconnect-core')(require('shoe'))
var widget = require('reconnect-widget')
var r = reconnect(function (stream) {
  ...
}).connect(...)
document.body.appendChild(widget(r))
```

**Comment by nrw** [comment]
I should have just reported this bug with the "invert" example. That would have been clearer. Thanks for working this out!

**Comment by dominictarr** [comment]
no problem!
