### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by naturalnikhil** [dominictarr/reconnect#26]
# First time error on sudo npm install:

npm WARN deprecated find-file@0.1.4: Use the globby package instead

npm WARN deprecated CSSselect@0.7.0: the module is now available as 'css-select'

npm WARN optional dep failed, continuing fsevents@0.3.6
# After if you do npm install again, lots of unmet dependency : 

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-build/node_modules/download/node_modules/mkdirp,

npm WARN unmet dependency which is version 0.3.5

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/node_modules/mkdirp,

npm WARN unmet dependency which is version 0.3.5

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-build/node_modules/download/node_modules/mkdirp,

npm WARN unmet dependency which is version 0.3.5

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/mkdirp,

npm WARN unmet dependency which is version 0.3.5

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-build/node_modules/download/node_modules/mkdirp,

npm WARN unmet dependency which is version 0.3.5

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin/node_modules/bin-wrapper/node_modules/download/node_modules/mkdirp,

npm WARN unmet dependency which is version 0.3.5

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-build/node_modules/download/node_modules/mkdirp,

npm WARN unmet dependency which is version 0.3.5

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/download/node_modules/decompress/node_modules/tar/node_modules/fstream requires mkdirp@'0.5' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-pngquant/node_modules/pngquant-bin/node_modules/bin-wrapper/node_modules/download/node_modules/mkdirp,

npm WARN unmet dependency which is version 0.3.5

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-google-cdn/node_modules/bower requires chalk@'^1.0.0' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-google-cdn/node_modules/chalk,

npm WARN unmet dependency which is version 0.5.1

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-google-cdn/node_modules/google-cdn/node_modules/bower requires chalk@'0.5.0' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-google-cdn/node_modules/chalk,

npm WARN unmet dependency which is version 0.5.1

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-google-cdn/node_modules/google-cdn/node_modules/cdnjs-cdn-data requires semver@'~2.2.1' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-google-cdn/node_modules/google-cdn/node_modules/semver,

npm WARN unmet dependency which is version 2.3.2

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-mocha-test/node_modules/mocha/node_modules/jade requires commander@'0.6.1' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-mocha-test/node_modules/mocha/node_modules/commander,

npm WARN unmet dependency which is version 2.0.0

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-mocha-test/node_modules/mocha/node_modules/jade requires mkdirp@'0.3.0' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-mocha-test/node_modules/mocha/node_modules/mkdirp,

npm WARN unmet dependency which is version 0.3.5

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-node-inspector/node_modules/node-inspector requires express@'^4.8.0' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/express,

npm WARN unmet dependency which is version 4.0.0

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-node-inspector/node_modules/node-inspector requires serve-favicon@'^2.1.1' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/serve-favicon,

npm WARN unmet dependency which is version 2.0.1

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-nodemon/node_modules/nodemon/node_modules/update-notifier/node_modules/request/node_modules/har-validator requires chalk@'^1.0.0' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/grunt-nodemon/node_modules/nodemon/node_modules/update-notifier/node_modules/chalk,

npm WARN unmet dependency which is version 0.4.0

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/karma/node_modules/http-proxy requires colors@'0.x.x' but will load

npm WARN unmet dependency /home/naturalnikhil/referdost/jobs_app/node_modules/karma/node_modules/colors,

npm WARN unmet dependency which is version 1.1.2

grunt-build-control@0.1.3 node_modules/grunt-build-control

└── shelljs@0.2.6

Please help in rectifying it. I'm an npm newbie.
Thanks.

**Comment by juliangruber** [comment]
Those are just WARNings, so the installation still worked. When doing `npm install XXX` you don't need  to and shouldn't use `sudo` as that is a security risk. The deprecated modules from your first install don't seem to have anything to do with `reconnect`, and the other unmed dependencies are probably due to your whole dependency tree not being up2date, ie some of your dependencies are outdated.

**Comment by alexnix** [comment]
Hi,
I work with @naturalnikhil  on that project.

What do you mean dependencies are outdated ? The exact same project can be installed on my PC without any problems.

Probably not all the dependencies in package.json specify the latest version but I can`t see why that should be a problem.

**Comment by naturalnikhil** [comment]
Thanks @juliangruber  for looking into it. Can you please guide us on the next steps to update dependencies and getting it work. I'm posting my package.json if it provides any clue.

Package.json:
===========
{
  "name": "jobs-client",
  "version": "0.0.0",
  "main": "server/app.js",
  "dependencies": {
    "express": "~4.0.0",
    "morgan": "~1.0.0",
    "body-parser": "~1.5.0",
    "method-override": "~1.0.0",
    "serve-favicon": "~2.0.1",
    "cookie-parser": "~1.0.1",
    "express-session": "~1.0.2",
    "errorhandler": "~1.0.0",
    "compression": "~1.0.1",
    "lodash": "~2.4.1",
    "ejs": "~0.8.4",
    "composable-middleware": "^0.3.0",
    "connect-mongo": "^0.4.1"
  },
  "devDependencies": {
    "connect-livereload": "~0.4.0",
    "grunt": "~0.4.4",
    "grunt-angular-templates": "^0.5.4",
    "grunt-asset-injector": "^0.1.0",
    "grunt-autoprefixer": "~0.7.2",
    "grunt-build-control": "DaftMonk/grunt-build-control",
    "grunt-concurrent": "~0.5.0",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-concat": "~0.4.0",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-cssmin": "~0.9.0",
    "grunt-contrib-htmlmin": "~0.2.0",
    "grunt-contrib-imagemin": "~0.7.1",
    "grunt-contrib-jshint": "~0.10.0",
    "grunt-contrib-less": "^0.11.0",
    "grunt-contrib-uglify": "~0.4.0",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-dom-munger": "^3.4.0",
    "grunt-env": "~0.4.1",
    "grunt-express-server": "~0.4.17",
    "grunt-google-cdn": "~0.4.0",
    "grunt-karma": "~0.8.2",
    "grunt-mocha-test": "~0.10.2",
    "grunt-newer": "~0.7.0",
    "grunt-ng-annotate": "^0.2.3",
    "grunt-node-inspector": "~0.1.5",
    "grunt-nodemon": "~0.2.0",
    "grunt-open": "~0.2.3",
    "grunt-protractor-runner": "^1.1.0",
    "grunt-rev": "~0.1.0",
    "grunt-svgmin": "~0.4.0",
    "grunt-usemin": "~2.1.1",
    "grunt-wiredep": "~1.8.0",
    "jit-grunt": "^0.9.1",
    "jshint-stylish": "~0.1.5",
    "karma": "~0.12.9",
    "karma-chrome-launcher": "~0.1.3",
    "karma-coffee-preprocessor": "~0.2.1",
    "karma-firefox-launcher": "~0.1.3",
    "karma-html2js-preprocessor": "~0.1.0",
    "karma-jade-preprocessor": "0.0.11",
    "karma-jasmine": "~0.1.5",
    "karma-ng-html2js-preprocessor": "~0.1.0",
    "karma-ng-jade2js-preprocessor": "^0.1.2",
    "karma-ng-scenario": "~0.1.0",
    "karma-phantomjs-launcher": "~0.1.4",
    "karma-requirejs": "~0.2.1",
    "karma-script-launcher": "~0.1.0",
    "open": "~0.0.4",
    "requirejs": "~2.1.11",
    "should": "~3.3.1",
    "supertest": "~0.11.0",
    "time-grunt": "~0.3.1"
  },
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "start": "node server/app.js",
    "test": "grunt test",
    "update-webdriver": "node node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update"
  },
  "private": true
}

**Comment by naturalnikhil** [comment]
It got fixed, we've to sync-up the versions of npm & node corresponding to the dependency versions.

Thanks for your time.
