### ISSUE TITLE
function api

### ISSUE THREAD

**Issue by juliangruber** [dominictarr/reconnect#3]
What about

``` js
var stream = reconnect(port)
```

ff you don't need logic to happen on connect?

**Comment by dominictarr** [comment]
Each communication abstraction handles disconnections differently.
(compare dnode with scuttlebutt for example)

You _could_ make a module that gave a stream that reconnected transparently,
but it wouldn't be appropriate in the general case.

**Comment by Raynos** [comment]
A module that gave a stream that reconnected transparently is called https://github.com/Raynos/boot

boot is cool if you want that. 20% of the time you don't want that and then it's just silly.
